# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creamery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creamery.Flavor')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creamery.Topping')),
            ],
        ),
    ]
